### ISSUE TITLE
Documentation: incorrect rules examples

### ISSUE THREAD

**Issue by cengels** [KeisukeYamashita/commitlint-rs#254]
**Describe the bug**

In the docs, some rules seem to have incorrect examples:

* [Scope empty](https://keisukeyamashita.github.io/commitlint-rs/rules/scope-empty/) shows an empty type in the "bad" example instead of an empty scope.
* [Scope format](https://keisukeyamashita.github.io/commitlint-rs/rules/scope-format/) shows an incorrectly formatted description in the "bad" example instead of an incorrectly formatted scope.
* [Scope max length](https://keisukeyamashita.github.io/commitlint-rs/rules/scope-max-length/) reads "Description length should be less than or equal to 72" under the example heading.
* [Type](https://keisukeyamashita.github.io/commitlint-rs/rules/type/) shows the example from [scope](https://keisukeyamashita.github.io/commitlint-rs/rules/scope/).
* [Type empty](https://keisukeyamashita.github.io/commitlint-rs/rules/type-empty/) shows an empty scope, not an empty type.
* [Type format](https://keisukeyamashita.github.io/commitlint-rs/rules/type-format/) has the same problem as scope format.

The defaults may also not be up-to-date anymore – for instance, when I ran `commitlint` without any configuration file and only a single-line commit, it printed `description is empty or missing space in the beginning` even though the default for the [body empty](https://keisukeyamashita.github.io/commitlint-rs/rules/body-empty/) rule is documented to be `ignore`.

## Config

N/A

## Error message

N/A

## Expected behavior

N/A

## Version

```console
0.1.6
```

## Additional context
N/A

**Comment by KeisukeYamashita** [comment]
Thank you very much for your detailed report, I'll fix it soon 🏃
