### ISSUE TITLE
commitlint --edit should take an argument

### ISSUE THREAD

**Issue by jceb** [KeisukeYamashita/commitlint-rs#372]
As pointed out in #289, the `--edit` flag doesn't take an argument. However, according to the documentation and according to the behavior of @commitlint/cli it should take an argument:

> -e, --edit             Read last commit from the specified file or fallbacks to ./.git/COMMIT_EDITMSG

## Error message

Please paste the error message below:

```
commitlint -e .git/COMMIT_EDITMSG
   error: unexpected argument '.git/COMMIT_EDITMSG' found

   Usage: commitlint [OPTIONS]

   For more information, try '--help'.
```

## Expected behavior

The argument should be accepted + the contents of the file should be evaluated as commit message.

## Version

```console
# Run the following command
$ commitlint --version
commitlint-rs 0.1.11
```

**Comment by KeisukeYamashita** [comment]
@jceb  Thank you for reaching out! 
I'll take a look today or this weekend.
