### ISSUE TITLE
Add each platform binaries to GitHub releases

### ISSUE THREAD

**Issue by KeisukeYamashita** [KeisukeYamashita/commitlint-rs#45]
## Why

Because in some cases, users want to download the binary directly and not from the Cargo or using Docker.
Therefore, we should add it to the GitHub release just like other toolings.

## Ref

* [cross-rs/cross](https://github.com/cross-rs/cross): “Zero setup” cross compilation and “cross testing” of Rust crates

**Comment by suyulin** [comment]
I'd like to take ownership of this issue

**Comment by KeisukeYamashita** [comment]
Thank you very much 👍

**Comment by KeisukeYamashita** [comment]
![Screenshot-2024-02-16 at 23 40 48@2x](https://github.com/Keis👍 keYamashita/commitlint-rs/assets/23056537/2384c2a0-6ab5-4062-bb60-c6f5cf775207)

Done 💯
